### ISSUE TITLE
Buffered Array Proxy

### ISSUE THREAD

**Issue by offirgolan** [yapplabs/ember-buffered-proxy#36]
I currently have a buffered array proxy implementation that follows the current buffered object proxy API structure. Do you think that you'd be interested in a PR or should I create a separate addon for it?

**Comment by lukemelia** [comment]
@offirgolan I'd say a separate addon, and I can link to it from this addon's README

**Comment by offirgolan** [comment]
👍 sounds good. I'll close this then.

**Comment by offirgolan** [comment]
@lukemelia [ember-buffered-array-proxy](https://github.com/offirgolan/ember-buffered-array-proxy) 😸
