### ISSUE TITLE
Buffered Proxy with Ember 3.6+

### ISSUE THREAD

**Issue by Arijit-Roy** [yapplabs/ember-buffered-proxy#42]
I am facing an issue with buffered proxy with ember 3.6+. `setUnknownProperty` function is what is causing this issue. Anyone else is facing any issue in this function ? It basically sets `hasBufferedChanges` to true when it is supposed to be false.

**Comment by lukemelia** [comment]
A contributor has mentioned that this issues is resolved by the following PR: https://github.com/yapplabs/ember-buffered-proxy/pull/41. If you're able to confirm that fixes your issue, that would be helpful.

**Comment by Arijit-Roy** [comment]
Yes. I can confirm that my issue is resolved by the PR #41.  Thank you for your response @lukemelia .
