### ISSUE TITLE
Release new version: 2.0.0

### ISSUE THREAD

**Issue by tniezurawski** [yapplabs/ember-buffered-proxy#55]
@lukemelia Can we release a new version of this addon? I propose a major version bump because we have a breaking change.

Here is the comparison: https://github.com/yapplabs/ember-buffered-proxy/compare/v1.0.1...master

**Changelog:**
- [Breaking Change] Drop support for Ember < 3.8
- [Maintanance] Bump Ember from 2.15 to 3.14
- [Bug fix] Buffered properties are not refreshing on Ember 3.13 (https://github.com/yapplabs/ember-buffered-proxy/issues/48)

**Comment by tniezurawski** [comment]
I published it as `2.0.0-beta.0` release.

**Comment by lukemelia** [comment]
👍 Thanks for taking the initiative @tniezurawski. I'm moving into an apartment in Singapore so I'm pretty distracted.
